-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 11:42:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `id_cursos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `quantidade` INT NULL,
  `formacao` INT NULL,
  `duracao` DOUBLE NULL,
  PRIMARY KEY (`id_cursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `idade` DATE NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especializacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especializacao` (
  `id_especializacao` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `data_criacao` DATE NULL,
  PRIMARY KEY (`id_especializacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores` (
  `id_professores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `idade` DATE NULL,
  `id_especializacao` INT NOT NULL,
  PRIMARY KEY (`id_professores`),
  CONSTRAINT `fk_Professores_Especializacao`
    FOREIGN KEY (`id_especializacao`)
    REFERENCES `mydb`.`Especializacao` (`id_especializacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas` (
  `id_turma` INT NOT NULL,
  `num_turma` INT NULL,
  `id_professores` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  `id_cursos` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  CONSTRAINT `fk_Turmas_Professores1`
    FOREIGN KEY (`id_professores`)
    REFERENCES `mydb`.`Professores` (`id_professores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_Aluno1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_Cursos1`
    FOREIGN KEY (`id_cursos`)
    REFERENCES `mydb`.`Cursos` (`id_cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidades` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `localidade` VARCHAR(255) NULL,
  `id_cursos` INT NOT NULL,
  PRIMARY KEY (`id_unidade`),
  CONSTRAINT `fk_unidades_Cursos1`
    FOREIGN KEY (`id_cursos`)
    REFERENCES `mydb`.`Cursos` (`id_cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
